# Mr. Advice MVVM appveyor.yml script

branches:
  only:
    - master
    - project-cleanup

version: '{branch}-{build}'

os: Visual Studio 2022
#install:
#  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

before_build:
  nuget restore "MrAdvice.MVVM.sln"

#nuget:
#  account_feed: true
#  project_feed: true
#  disable_publish_on_pr: true

configuration: Release
platform: Any CPU

build:
  parallel: true
  project: 'MrAdvice.MVVM.sln'
#  publish_nuget: true
#  publish_nuget_symbols: true

artifacts:
  - path: 'MrAdvice.MVVM.WPF\bin\$(Configuration)\*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: QsAfyY+46GeTCjC+L2kjV6/1AriR3nxjHm8EUru4epPuwl9IHaqAlC13H5TCWyBF
  skip_symbols: false

after_test:
  ps: Get-ChildItem .\MrAdvice.MVVM.*.nupkg -Recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
