# Mr. Advice MVVM appveyor.yml script

branches:
  only:
    - master

version: '{branch}-{build}'

os: Visual Studio 2022

before_build:
  nuget restore "MrAdvice.MVVM.sln"

configuration: Release

build:
  parallel: true
  project: 'MrAdvice.MVVM.sln'
  publish_nuget: false
  publish_nuget_symbols: false
  verbosity: minimal

artifacts:
  - path: 'MrAdvice.MVVM.WPF\bin\$(Configuration)\*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: FXdfurOFdTV/iNGNBf9Vqb3teeqGMrwuMxpoWQMVzHsZ9roqoCCGOQxrzhRM5Wwm
  skip_symbols: false

after_test:
  ps: Get-ChildItem .\MrAdvice.MVVM.*.nupkg -Recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
